/* HerDay second testing batch. All writes use authorized server RPCs. */
async function herdayUploadFetch(worker,payload,token){let error;for(let attempt=0;attempt<2;attempt++){try{return await fetch(worker+'/v1/upload',{method:'POST',headers:{Authorization:'Bearer '+token},body:payload,cache:'no-store',redirect:'error',referrerPolicy:'no-referrer'});}catch(e){error=e;}}throw error;}
async function herdayUploadFile(file,section,uploadId){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size<1||file.size>10*1048576)throw new Error('Use JPG, PNG or WebP up to 10 MB.');
 const {data,error}=await supabaseClient.auth.getSession();if(error)throw error;const token=data?.session?.access_token;if(!token)throw new Error('Session expired.');
 const payload=new FormData();payload.append('section',section);payload.append('file',await herdayOptimizeImage(file));payload.append('upload_id',uploadId);
 const response=await herdayUploadFetch((window.HERDAY_MEDIA_WORKER||'https://herday-media-api.urduwaveblog.workers.dev').replace(/\/+$/,''),payload,token),result=await response.json();
 if(!response.ok||result.ok!==true||result.section!==section||result.status!=='pending')throw new Error(result.error||'Image upload could not be confirmed. Retry uses the same upload ID.');return result.key;
}
function herdayEditAddImages(input){if(herdayEditBusy)return;const files=[...input.files];if(herdayEditing.images.length+files.length>5){alert('Maximum five images. Remove an image first.');input.value='';return;}for(const file of files)herdayEditing.images.push({file,uploadId:crypto.randomUUID(),url:URL.createObjectURL(file)});input.value='';herdayRenderEditImages();}
function herdayEditRemoveImage(index){if(herdayEditBusy)return;const item=herdayEditing.images.splice(index,1)[0];if(item.url)URL.revokeObjectURL(item.url);herdayRenderEditImages();}
async function herdayRenderEditImages(){
 const state=herdayEditing,box=document.getElementById('herdayEditImages');if(!state||!box)return;
 box.innerHTML=state.images.map((im,i)=>`<div class="herday-edit-image"><img alt="Attachment ${i+1}" ${im.url?`src="${esc(im.url)}"`:''}><button type="button" class="hm-btn secondary" onclick="herdayEditRemoveImage(${i})">Remove</button></div>`).join('')||'<p>No images. Add up to five.</p>';
 const imgs=[...box.querySelectorAll('img')];for(let i=0;i<state.images.length;i++){const im=state.images[i];if(!im.key)continue;try{const {data}=await supabaseClient.auth.getSession();const token=data?.session?.access_token;const endpoint=state.x.author_id===currentUser()?.id?'/v1/read':'/v1/moderation-preview';const worker=(window.HERDAY_MEDIA_WORKER||'https://herday-media-api.urduwaveblog.workers.dev').replace(/\/+$/,'');const response=await fetch(worker+endpoint+'?key='+encodeURIComponent(im.key),{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!response.ok)throw new Error();const url=URL.createObjectURL(await response.blob());if(herdayEditing!==state||!imgs[i]?.isConnected){URL.revokeObjectURL(url);continue;}im.url=url;imgs[i].src=url;}catch(_){if(imgs[i]?.isConnected)imgs[i].alt='Preview unavailable; existing attachment '+(i+1);}}
}
const herdayCloseEditBeforeMedia=herdayCloseEdit;
herdayCloseEdit=function(){if(herdayEditBusy)return;for(const im of herdayEditing?.images||[])if(im.url)URL.revokeObjectURL(im.url);herdayCloseEditBeforeMedia();};
async function herdayRetryEditCleanup(id){try{await herdayMediaAction('/v1/edit/cleanup',{submission_id:id,confirm:true});await loadMyPosts();poetrySuccessNotice('Removed images cleaned up.');}catch(error){alert('Cleanup needs retry: '+error.message);}}
const herdayLoadMineBeforeCleanup=loadMyPosts;
loadMyPosts=async function(more=false){await herdayLoadMineBeforeCleanup(more);const owner=currentUser()?.id,box=document.getElementById('myPostsList');if(!box||!owner)return;try{const jobs=await herdayRpc('herday_pending_edit_cleanup_v2');if(!box.isConnected||owner!==currentUser()?.id)return;box.querySelectorAll('[data-edit-cleanup]').forEach(x=>x.remove());for(const j of jobs)box.insertAdjacentHTML('beforeend',`<div class="my-post-card" data-edit-cleanup><p>Changes saved. Removed image cleanup needs confirmation.</p><button class="btn secondary" onclick="herdayRetryEditCleanup('${j.id}')">Retry Image Cleanup</button></div>`);}catch(_){/* Post list remains usable; retry refresh for cleanup status. */}};
let herdaySaved={owner:null,rows:[],loaded:false,loading:false,more:false,error:'',request:0};
function herdaySavedReset(){herdaySaved={owner:null,rows:[],loaded:false,loading:false,more:false,error:'',request:herdaySaved.request+1};}
function herdaySavedPage(){if(!currentUser())return '';if(herdaySaved.owner!==currentUser().id)herdaySavedReset();if(!herdaySaved.loaded&&!herdaySaved.loading)setTimeout(()=>herdayLoadSaved(),0);return `<section class="poetry-page">${poetryHeader(isAdmin()?'admin-profile':'user-profile','Saved Posts','Your saved poetry')}<div class="poetry-feed">${herdaySaved.error?`<p role="alert">${esc(herdaySaved.error)} <button onclick="herdayLoadSaved()">Retry</button></p>`:!herdaySaved.loaded?'<p>Loading saved posts…</p>':herdaySaved.rows.map(p=>poetryCard(p)).join('')||'<p>No saved posts yet.</p>'}${herdaySaved.more?`<button class="btn secondary" onclick="herdayLoadSaved(true)" ${herdaySaved.loading?'disabled':''}>Load more</button>`:''}</div></section>`;}
async function herdayLoadSaved(more=false){if(!currentUser()||herdaySaved.loading)return;const state=herdaySaved,owner=currentUser().id,serial=++state.request;state.loading=true;state.error='';try{const last=more?state.rows.at(-1):null;const rows=await herdayRpc('herday_saved_poetry_v2',{p_before_created_at:last?.created_at||null,p_before_id:last?.id||null});await herdayIdentities(rows.map(r=>r.author_id));const cats=await poetryFetchActiveCategories(),posts=rows.map(r=>herdayAdaptPost(r,cats));await herdayRefreshActions(posts);if(herdaySaved!==state||serial!==state.request||owner!==currentUser()?.id)return;state.owner=owner;state.rows=more?[...state.rows,...posts.filter(p=>!state.rows.some(x=>x.id===p.id))]:posts;state.more=rows.length===30;state.loaded=true;herdayContent.posts=[...herdayContent.posts.filter(p=>!posts.some(x=>x.id===p.id)),...posts];}catch(e){state.error=e.message;state.loaded=true;}finally{state.loading=false;if(S.route==='saved-posts'&&owner===currentUser()?.id)render();}}
const herdaySetActionBeforeSaved=herdaySetAction;
herdaySetAction=async function(id,action){await herdaySetActionBeforeSaved(id,action);if(action==='save'){const p=herdayContent.posts.find(x=>x.id===id);if(p&&!p.saved)herdaySaved.rows=herdaySaved.rows.filter(x=>x.id!==id);herdaySaved.loaded=false;if(S.route==='saved-posts'){await herdayLoadSaved();render();}}};

// Post cards from Saved Posts use the same detail route and real IDs.
const herdayOpenPostBeforeSaved=poetryOpenPost;
poetryOpenPost=function(key,comments=false){if(S.route==='saved-posts')return nav('poetry-post',{poetryPostKey:key,poetryReturn:'saved-posts'}).then(()=>{if(comments)document.getElementById('poetryComments')?.scrollIntoView();});return herdayOpenPostBeforeSaved(key,comments);};
function poetryComment(c){const photo=herdayFix.identities[c.author_id]?.photo,state=herdayCommentState(S.poetryPostKey),parent=state.rows.find(r=>r.id===c.parent_comment_id);return `<div class="poetry-comment ${c.parent_comment_id?'herday-comment-reply':''}">${photo?`<img class="poetry-avatar" src="${esc(photo)}" alt="">`:`<span class="poetry-avatar poetry-user-initial">${esc(c.author.slice(0,1))}</span>`}<div class="poetry-comment-copy"><b>${esc(c.author)}</b><time>${esc(c.time)}</time>${c.parent_comment_id?`<small>Reply to ${esc(parent?herdayContent.authors[parent.author_id]||'comment':'earlier comment')}</small>`:''}<p dir="auto">${esc(c.body)}</p><div class="herday-comment-actions"><button class="${c.liked?'is-on':''}" aria-pressed="${!!c.liked}" onclick="herdayLikeComment('${c.id}')">♡ ${Number(c.likes)||''}</button><button onclick="herdayReplyComment('${c.id}')">Reply</button></div>${state.rows.filter(r=>r.parent_comment_id===c.id).map(r=>poetryComment({...r,author:herdayContent.authors[r.author_id]||'HerDay User',time:herdayTime(r.created_at)})).join('')}</div>${c.author_id===currentUser()?.id||isAdmin()?`<button class="poetry-menu" data-poetry-action="comment-menu" data-comment-id="${esc(c.id)}" aria-label="Comment options">${poetryIcon('menu')}</button>`:''}</div>`;}

async function herdayLikeComment(id){if(!currentUser())return nav('login');const c=herdayCommentState(S.poetryPostKey).rows.find(r=>r.id===id),key='comment'+id;if(!c||herdayFix.actionBusy.has(key))return;herdayFix.actionBusy.add(key);try{await herdayRpc('herday_like_comment_v2',{p_comment_id:id,p_enabled:!c.liked});await herdayLoadComments(S.poetryPostKey);}catch(e){alert(e.message);}finally{herdayFix.actionBusy.delete(key);}}
function herdayReplyComment(id){if(!currentUser())return nav('login');const state=herdayCommentState(S.poetryPostKey);state.replyId=id;state.request=null;render();setTimeout(()=>{const input=document.querySelector('[data-poetry-composer] input');input?.focus();},0);}
function herdayCancelReply(){herdayCommentState(S.poetryPostKey).replyId=null;render();}
const herdayComposerBeforeReply=poetryComposer;
poetryComposer=function(post){const state=herdayCommentState(post.id),c=state.rows.find(r=>r.id===state.replyId);return (c?`<div class="herday-reply-label">Replying to ${esc(herdayContent.authors[c.author_id]||'comment')} <button onclick="herdayCancelReply()">Cancel reply</button></div>`:'')+herdayComposerBeforeReply(post);};
async function herdayModeratorDelete(id){const reason=prompt('Reason for deleting this post (required):');if(!reason?.trim())return;if(!confirm('Delete this post and its images? The reason and your action will remain in Admin history.'))return;try{await herdayMediaAction('/v1/moderator/delete-content',{submission_id:id,confirm:true,reason:reason.trim()});herdayContent.loaded=false;await nav(S.route==='mod-review'?'mod-queue':S.route);poetrySuccessNotice('Post deleted; reason recorded.');}catch(error){alert('Deletion could not be confirmed: '+error.message+' Retry with the same post ID.');}}
function herdayHistoryDay(delta=0){const now=new Date();now.setTime(now.getTime()+delta*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
function herdayHistoryDate(value){if(herdayAdminHistory.loading)return;herdayAdminHistory.date=value;herdayAdminHistory.loaded=false;herdayAdminLoadHistory(true);}
async function herdayClearHistory(){const h=herdayAdminHistory,rows=h[h.tab],ids=rows.filter(r=>h.tab!=='deletions'||r.media_deleted_at).map(r=>r.id||r.submission_id);if(!ids.length)return;if(!confirm('Clear these displayed records from your History page? Posts and stored audit records will remain.'))return;try{for(let i=0;i<ids.length;i+=100)await herdayRpc('herday_hide_history_v2',{p_kind:h.tab,p_ids:ids.slice(i,i+100)});await herdayAdminLoadHistory(true);}catch(e){alert(e.message);}}

async function herdayShowDeleteAction(menu,key){const owner=currentUser()?.id;try{const perms=await herdayRpc('herday_delete_permissions_v2');const section=herdayContent.posts.find(p=>p.id===key)?.section_key||'poetry';const r=perms.find(p=>p.moderator_id===owner&&p.section_key===section);if(menu.isConnected&&currentUser()?.id===owner&&r?.can_delete)menu.querySelector('[data-moderator-delete]').hidden=false;}catch(_){} }
