const B={
 cats:['Makeup','Bridal Services','Hair','Mehndi','Skin & Facial','Waxing','Threading & Brows','Nails','Manicure & Pedicure','Lashes','Massage & Relaxation','Other Beauty Services'],
 quick:['Makeup','Hair','Mehndi','Skin & Facial','Nails','Waxing'],
 providers:[
  {id:'ayesha',name:'Glam by Ayesha',verified:true,cats:['Makeup','Bridal Services'],services:['Party Makeup','Bridal Makeup','Engagement Makeup'],areas:['DHA Phase 5','DHA Phase 6','Askari 11'],about:'Professional makeup artist offering elegant, personalized beauty services for your special moments.',rating:4.8,count:37,completed:127},
  {id:'noor',name:'Noor Beauty Studio',verified:true,cats:['Hair','Skin & Facial'],services:['Hair Styling','Facial','Hair Treatment'],areas:['DHA Phase 5','Gulberg'],about:'Beauty care with a calm, personal touch.',rating:4.7,count:22,completed:81},
  {id:'zara',name:'Zara Beauty Artistry',verified:true,cats:['Makeup','Mehndi'],services:['Party Makeup','Mehndi'],areas:['DHA Phase 5','Askari 11'],about:'Makeup and mehndi services for events and celebrations.',rating:4.9,count:18,completed:54}
 ],
 reviews:[{provider:'ayesha',name:'Sara Khan',stars:5,date:'12 Sep 2026',text:'Beautiful makeup and a very comfortable experience.',confirmed:true},{provider:'ayesha',name:'Amina',stars:4,date:'28 Aug 2026',text:'Really liked the final look. The service was professional and friendly.',confirmed:true}],
 contacts:[{id:'c1',provider:'ayesha',customer:'Sara Khan',service:'Party Makeup',status:'contacted'},{id:'c2',provider:'ayesha',customer:'Amina',service:'Bridal Services',status:'waiting'},{id:'c3',provider:'ayesha',customer:'Hira',service:'Hair Styling',status:'confirmed'}]
};
const LS='herdayBeautyV1';let S=JSON.parse(localStorage.getItem(LS)||'{}');S={route:'home',location:'DHA Phase 5',category:'Makeup',...S};const save=()=>localStorage.setItem(LS,JSON.stringify(S));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const $=q=>document.querySelector(q);const app=()=>$('#beautyApp');
function nav(route,data={}){Object.assign(S,data,{route});save();render();scrollTo(0,0)}
function head(title,sub='',back='beauty-main'){return `<div class="beauty-head"><button class="back" onclick="nav('${back}')">‹</button><div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div></div>`}
function bottom(){return `<div class="beauty-bottom-space"></div>`}
function setBeauty(on){$('#homePage').classList.toggle('hidden',on);$('#beautyApp').classList.toggle('hidden',!on);document.body.classList.toggle('beauty-mode',on)}
function render(){if(S.route==='home'){setBeauty(false);return}setBeauty(true);let h='';
 if(S.route==='beauty-main')h=main(); if(S.route==='categories')h=categories(); if(S.route==='results')h=results(); if(S.route==='profile')h=profile(S.provider||'ayesha'); if(S.route==='create')h=createProfile(); if(S.route==='verify-info')h=verifyInfo(); if(S.route==='pending')h=pending(); if(S.route==='contacts')h=contacts(); if(S.route==='confirm')h=confirmService(); if(S.route==='rate')h=rate(); app().innerHTML=h+bottom();}
function main(){return head('Beauty Services','Beauty, closer to you.','home')+`<div class="bcard"><div class="loc-grid"><button class="btn secondary" onclick="S.location='DHA Phase 5';save();render()">⌖ Near Me</button><button class="btn secondary" onclick="let x=prompt('Choose location',S.location);if(x){S.location=x;save();render()}">Choose Location</button></div><div style="margin-top:10px"><b>${esc(S.location)}</b><div class="muted">Find beauty professionals who serve this area.</div></div></div><input class="searchbox" placeholder="What service are you looking for?" onkeydown="if(event.key==='Enter'){S.category=this.value||'Makeup';nav('results')}"><div class="row between"><h2 class="section-title">Explore Beauty</h2><button class="danger-link" onclick="nav('categories')">View all</button></div><div class="quick-grid">${B.quick.map(c=>`<button class="quick" onclick="nav('results',{category:'${c}'})"><b>${c}</b><span>Explore services</span></button>`).join('')}</div><div style="height:12px"></div><button class="btn primary" onclick="nav('results')">Find Providers</button><div class="bcard provider-cta"><b>Do you offer beauty services?</b><div class="muted" style="margin:4px 0 10px">Create your professional Beauty Profile on HerDay.</div><button class="btn secondary" onclick="nav('create')">Create Beauty Profile</button></div>`}
function categories(){return head('All Beauty Categories','What are you looking for?')+`<div class="cat-grid">${B.cats.map(c=>`<button class="cat" onclick="nav('results',{category:'${c}'})"><b>${c}</b><span>Find professionals</span></button>`).join('')}</div>`}
function results(){let ps=B.providers.filter(p=>p.areas.includes(S.location)&& (p.cats.includes(S.category)||p.services.some(x=>x.toLowerCase().includes(S.category.toLowerCase())))); if(!ps.length)ps=B.providers.filter(p=>p.areas.includes(S.location));return head('Beauty Professionals',`${esc(S.category)} · ${esc(S.location)}`)+`<div class="bcard"><div class="row between"><div><span class="muted">Service</span><br><b>${esc(S.category)}</b></div><button class="pill" onclick="nav('categories')">Change Service</button></div><hr style="border:0;border-top:1px solid #f0e2e7"><div class="row between"><div><span class="muted">Location</span><br><b>${esc(S.location)}</b></div><button class="pill" onclick="let x=prompt('Choose location',S.location);if(x){S.location=x;save();render()}">Change Location</button></div></div><div class="muted">Showing professionals who serve this area.</div><h2 class="section-title">Matching Professionals</h2><div class="muted">${ps.length} results</div>${ps.length?ps.map(p=>providerCard(p)).join(''):`<div class="empty">No matching professionals found for this location.</div>`}`}
function providerCard(p){return `<div class="bcard provider-card"><div class="avatar">♙</div><div><div><b>${p.name}</b> ${p.verified?'<span class="verified">✓</span>':''}</div><div class="muted">${p.cats.join(' · ')}</div><div style="font-size:10px;margin:5px 0">${p.services.slice(0,2).join(' · ')}</div><div class="muted">Serves: ${p.areas.join(', ')}</div><button class="btn primary small" style="margin-top:8px" onclick="nav('profile',{provider:'${p.id}'})">View Profile</button></div></div>`}
function profile(id){let p=B.providers.find(x=>x.id===id)||B.providers[0];let rv=[...B.reviews,...(S.reviews||[])].filter(r=>r.provider===p.id);return head('Beauty Profile','', 'results')+`<div class="bcard" style="text-align:center"><div class="avatar" style="width:96px;height:96px;margin:auto;font-size:45px">♙</div><h2 style="font:26px DMSerif;margin:10px 0 2px">${p.name} ${p.verified?'<span class="verified">✓</span>':''}</h2><div class="chips" style="justify-content:center">${p.cats.map(c=>`<span class="chip">${c}</span>`).join('')}</div></div><div class="metric-grid"><div class="metric"><b>★ ${p.rating}</b><span class="muted">${p.count+(S.extraRatings||0)} ratings</span></div><div class="metric"><b>${p.completed+(S.extraCompleted||0)}</b><span class="muted">Services Completed</span></div></div><h2 class="section-title">About</h2><div class="bcard muted">${p.about}</div><h2 class="section-title">Services</h2><div class="bcard service-list">${p.services.map(x=>`<div class="service-row">${x}</div>`).join('')}</div><h2 class="section-title">Service Areas</h2><div class="chips">${p.areas.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div style="height:14px"></div><button class="btn green" onclick="contact('${p.id}')">Contact on WhatsApp</button><h2 class="section-title">Ratings & Reviews</h2>${rv.length?`<div class="bcard"><div class="row between"><div><b style="font:24px DMSerif">${p.rating}</b> <span class="stars">★★★★★</span></div><span class="muted">${p.count+(S.extraRatings||0)} ratings</span></div>${rv.map(reviewCard).join('')}</div>`:`<div class="bcard empty">No reviews yet.</div>`}`}
function reviewCard(r){return `<div class="review"><div class="row between"><b>${esc(r.name)}</b><span class="muted">${esc(r.date)}</span></div><div class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</div><div style="font-size:10px;margin:5px 0">${esc(r.text)}</div><div class="row between"><span class="muted">${r.confirmed?'✓ Confirmed Service':''}</span><button class="danger-link" onclick="alert('Review reported for HerDay moderation.')">Report Review</button></div></div>`}
function contact(pid){let id='u'+Date.now();S.contacts=[...(S.contacts||[]),{id,provider:pid,customer:'Tanveer',service:S.category||'Beauty Service',status:'contacted'}];save();alert('HerDay Contact Request created. WhatsApp would now open in production.');}
function createProfile(){let sel=S.newCats||[];return head('Create Beauty Profile','Create your professional Beauty Profile on HerDay.')+`<div class="bcard"><label class="field-label">Professional Photo</label><div class="avatar">♙</div><input class="field" type="file" accept="image/*"><label class="field-label">Professional / Parlor Name</label><input id="proName" class="field" value="${esc(S.newName||'')}"><label class="field-label">About</label><textarea id="proAbout" class="field">${esc(S.newAbout||'')}</textarea><label class="field-label">Beauty Categories</label><div class="drop"><button class="field" style="text-align:left" onclick="$('#catDrop').classList.toggle('hidden')">Select categories ▾</button><div id="catDrop" class="drop-menu hidden">${B.cats.map(c=>`<label><input type="checkbox" ${sel.includes(c)?'checked':''} onchange="toggleCat('${c}',this.checked)">${c}</label>`).join('')}<button class="btn primary small" onclick="$('#catDrop').classList.add('hidden')">Done</button></div></div><div class="chips" style="margin-top:7px">${sel.map(c=>`<span class="chip">${c} ×</span>`).join('')}</div><label class="field-label">Your Services</label><input id="proServices" class="field" placeholder="e.g. Party Makeup, Bridal Makeup" value="${esc(S.newServices||'')}"><label class="field-label">Service Areas</label><input id="proAreas" class="field" placeholder="e.g. DHA Phase 5, Askari 11" value="${esc(S.newAreas||'')}"><div class="notice" style="margin-top:7px">Select standardized official area names so customers can find you correctly.</div><label class="field-label">WhatsApp Number</label><input id="proPhone" class="field" inputmode="tel" value="${esc(S.newPhone||'')}"></div><button class="btn primary" onclick="saveCreate()">Continue to Verification</button>`}
function toggleCat(c,on){let a=new Set(S.newCats||[]);on?a.add(c):a.delete(c);S.newCats=[...a];save()}
function saveCreate(){S.newName=$('#proName').value.trim();S.newAbout=$('#proAbout').value.trim();S.newServices=$('#proServices').value.trim();S.newAreas=$('#proAreas').value.trim();S.newPhone=$('#proPhone').value.trim();save();nav('verify-info')}
function verifyInfo(){return head('Verify Your Profile','Complete live verification before your Beauty Profile can go public.','create')+`<div class="bcard"><b>Live Video Verification</b><span class="pill" style="float:right">Live camera only</span><div class="info-line">✓ <span>Use your front camera and keep your face clearly visible.</span></div><div class="info-line">✓ <span>Gallery and prerecorded video uploads are not accepted.</span></div><div class="info-line">✓ <span>Your verification video is private and never appears on your public profile.</span></div></div><button class="btn primary" onclick="startCamera()">Start Camera Verification</button><h2 class="section-title">What happens next?</h2><div class="bcard muted">1 Record live video → 2 Submit → 3 HerDay review → 4 Approved profile becomes live and Verified ✓ activates. Girls’ Space access is also unlocked.</div><div class="notice">Privacy: video remains private while review is pending and is permanently deleted after successful approval.</div><h2 class="section-title">Need Help?</h2><div class="bcard"><b>WhatsApp Support</b><div class="muted">Leave a message or voice note. Live calls are not available 24 hours.</div><hr style="border:0;border-top:1px solid #f0e2e7"><b>Email Support</b><div class="muted">Responses may take 24–72 hours.</div></div>`}
let stream=null,rec=null,chunks=[];async function startCamera(){document.body.insertAdjacentHTML('beforeend',cameraHTML());try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});$('#camVideo').srcObject=stream}catch(e){$('#camMsg').textContent='Camera permission is required for live verification.'}}
function cameraHTML(){return `<div id="cameraScreen" class="camera-screen"><div class="camera-top"><button class="back" style="color:white" onclick="closeCamera()">×</button><b>Live Verification</b><span class="muted">Step 1 of 1</span></div><div class="camera-box"><video id="camVideo" autoplay muted playsinline></video><div class="face-guide"></div></div><div style="text-align:center"><b>Look directly at the camera</b><div id="camMsg" class="muted">Ready to record</div></div><div class="camera-actions" style="margin-top:14px"><button id="startRec" class="btn primary" onclick="recordStart()">Start Recording</button><button id="stopRec" class="btn secondary" disabled onclick="recordStop()">Stop</button><button id="retake" class="btn secondary hidden" onclick="retake()">Retake</button><button id="submitRec" class="btn primary" disabled onclick="submitVerification()">Submit for Review</button></div><div class="muted" style="text-align:center;margin:15px">1 Record — 2 Stop — 3 Submit</div><div class="notice" style="background:#2b222a;color:#d9cbd2;border-color:#e91e63">Private verification video. It is not public and is deleted after approval.</div></div>`}
function recordStart(){if(!stream)return;chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.start();$('#startRec').disabled=true;$('#stopRec').disabled=false;$('#camMsg').textContent='● REC — recording live';}
function recordStop(){if(rec&&rec.state==='recording')rec.stop();$('#stopRec').disabled=true;$('#retake').classList.remove('hidden');$('#submitRec').disabled=false;$('#camMsg').textContent='Video ready';}
function retake(){chunks=[];$('#retake').classList.add('hidden');$('#submitRec').disabled=true;$('#startRec').disabled=false;$('#camMsg').textContent='Ready to record'}
function closeCamera(){stream?.getTracks().forEach(t=>t.stop());$('#cameraScreen')?.remove()}
function submitVerification(){S.verification='pending';save();closeCamera();nav('pending')}
function pending(){return head('Verification Submitted','Your live verification has been submitted.','beauty-main')+`<div class="bcard" style="text-align:center"><div style="font-size:42px">✓</div><h2 style="font:24px DMSerif">Video Submitted Successfully</h2><span class="status wait">Pending Review</span></div><h2 class="section-title">What happens next?</h2><div class="bcard"><b>Beauty Profile</b><div class="muted">Awaiting Verification Approval</div><div class="notice" style="margin-top:10px">Your Beauty Profile is not public until approved.</div></div><div class="notice">Your verification video stays private while pending and is permanently deleted after approval.</div><div class="bcard"><b>No action needed</b><div class="muted">HerDay will review your verification.</div></div><button class="btn primary" onclick="nav('beauty-main')">Back to Beauty Services</button>`}
function allContacts(){return [...B.contacts,...(S.contacts||[])]}
function contacts(){let cs=allContacts();return head('Service Contacts','Manage customers who contacted you through HerDay.','beauty-main')+`<div class="notice">Customers who contacted your Beauty Profile through HerDay appear here.</div>${cs.map(c=>`<div class="bcard"><div class="row between"><b>${esc(c.customer)}</b>${status(c.status)}</div><div class="muted">Contacted through HerDay</div><div style="margin:8px 0;font-size:10px">Service: <b>${esc(c.service)}</b></div>${c.status==='contacted'?`<button class="btn primary small" onclick="markDone('${c.id}')">Mark Service Completed</button>`:''}</div>`).join('')}`}
function status(s){let m={contacted:['Contacted',''],waiting:['Waiting for Customer Confirmation','wait'],confirmed:['Completed & Confirmed','done'],no:['Not Confirmed','no']};let x=m[s]||[s,''];return `<span class="status ${x[1]}">${x[0]}</span>`}
function markDone(id){if(confirm('Mark service as completed?\nConfirm that you provided this beauty service.')){let c=(S.contacts||[]).find(x=>x.id===id);if(c)c.status='waiting';else{S.baseOverrides={...(S.baseOverrides||{}),[id]:'waiting'}}save();S.confirmId=id;nav('confirm')}}
function getContact(id){let c=(S.contacts||[]).find(x=>x.id===id)||B.contacts.find(x=>x.id===id);if(c&&S.baseOverrides?.[id])return {...c,status:S.baseOverrides[id]};return c}
function confirmService(){let c=getContact(S.confirmId||'c2')||B.contacts[1];return head('Confirm Service','Please confirm your recent beauty service.','beauty-main')+`<div class="bcard provider-card"><div class="avatar">♙</div><div><b>Glam by Ayesha <span class="verified">✓</span></b><div class="muted">Service Completed</div></div></div><div class="bcard"><b>Service Completed</b><div class="muted">Provider has marked this service as completed.</div><div style="margin-top:8px">${esc(c.service)}</div></div><div class="bcard"><h2 style="font:22px DMSerif">Did you receive this service?</h2><p class="muted">Confirm only if you actually received a beauty service from this professional.</p><button class="btn primary" onclick="confirmYes('${c.id}')">Yes, I Received the Service</button><div style="height:8px"></div><button class="btn secondary" onclick="confirmNo('${c.id}')">No, I Didn’t Receive the Service</button><div class="muted" style="margin-top:9px">Yes unlocks one Rate & Review opportunity. No does not.</div></div>`}
function setStatus(id,st){let c=(S.contacts||[]).find(x=>x.id===id);if(c)c.status=st;else S.baseOverrides={...(S.baseOverrides||{}),[id]:st};save()}
function confirmYes(id){setStatus(id,'confirmed');S.rateId=id;S.extraCompleted=(S.extraCompleted||0)+1;save();nav('rate')}
function confirmNo(id){setStatus(id,'no');alert('Service marked Not Confirmed. Rating was not unlocked.');nav('beauty-main')}
function rate(){let c=getContact(S.rateId||'c3')||B.contacts[2];return head('Rate Your Experience','Share your experience with this beauty professional.','beauty-main')+`<div class="bcard provider-card"><div class="avatar">♙</div><div><b>Glam by Ayesha <span class="verified">✓</span></b><div class="muted">✓ Service confirmed</div></div></div><h2 class="section-title">How was your experience?</h2><div class="rating-stars">${['Poor','Fair','Good','Very Good','Excellent'].map((x,i)=>`<div class="star-choice"><button class="${(S.tempStars||0)>i?'on':''}" onclick="S.tempStars=${i+1};save();render()">★</button>${i+1}<br>${x}</div>`).join('')}</div><h2 class="section-title">Write a Review</h2><textarea id="reviewText" class="field" placeholder="Tell others about your experience...">${esc(S.tempReview||'')}</textarea><div class="muted">You can edit your rating and review before submitting.</div><div style="height:10px"></div><button class="btn primary" onclick="submitReview('${c.id}')">Submit Review</button>`}
function submitReview(id){let stars=S.tempStars||0,text=$('#reviewText').value.trim();if(!stars){alert('Please select a star rating.');return}if(!text){alert('Please write a review.');return}S.reviews=[...(S.reviews||[]),{provider:'ayesha',name:'Tanveer',stars,date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),text,confirmed:true,contact:id}];S.extraRatings=(S.extraRatings||0)+1;S.tempStars=0;S.tempReview='';save();nav('profile',{provider:'ayesha'})}
window.nav=nav;window.toggleCat=toggleCat;window.saveCreate=saveCreate;window.startCamera=startCamera;window.closeCamera=closeCamera;window.recordStart=recordStart;window.recordStop=recordStop;window.retake=retake;window.submitVerification=submitVerification;window.contact=contact;window.markDone=markDone;window.confirmYes=confirmYes;window.confirmNo=confirmNo;window.submitReview=submitReview;
window.render=render;
